### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/share-to-mastodon#1]
Waiting until Firefox supports Manifest V3 and Service Workers. I may also investigate how much work it would be to maintain a separate Manifest V2 version (it might just need a different manifest file and nothing else?).

https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/

**Comment by corbindavenport** [comment]
Working on this in the `firefox` branch.

**Comment by corbindavenport** [comment]
Working on this now in the `firefox` branch.

**Comment by Krutonium** [comment]
It's worth noting that even the current release can have Manifest v3 Enabled via

```
about:config
extensions.manifestV3.enabled => true
```

**Comment by corbindavenport** [comment]
The Firefox release is now rolled out :)
