### ISSUE TITLE
Right-click options in web pages don't capture the "title" of the page one is attempting to share

### ISSUE THREAD

**Issue by corq** [corbindavenport/share-to-mastodon#14]
Reproduction:

If I'm visiting a web page in Chrome tht I wish to share on Mastodon, If I right click, I get a menu item to share with. However, this shares ONLY the link, not the headline/title or the page, UNLESS I highlight the chosen text before sharing, and then, I have to clean up the "quotemarks".

Conversely, If I'm visting a page, and chose to click the *toolbar* for the extension, I get a nice, natural-looking headline that's quick and contextual for social media. 

I've checked to be sure I don't have some other Mastodon sharing tool enabled. I find if given an option to "include page title" from the context menu,  I don't see a place to configure this headline inclusion. I've added all my desired servers to the list, it just seems like the "toolbar" behaves differently from the context menu actions. 

![type_something_here](https://github.com/corbindavenport/share-to-mastodon/assets/8109511/9a011d2d-9086-4ac5-832b-98dea6463b38)
![perfect](https://github.com/corbindavenport/share-to-mastodon/assets/8109511/5deab52c-185f-4847-906b-a3ab28605fd4)

**Comment by corbindavenport** [comment]
I thought the browser extension APIs didn't provide title information for the current tab from right-click menu options, but apparently I was wrong! Just tried a quick fix and it appears to work fine. If no issues show up in cross-browser testing, this will be in the next update, which should hopefully be soon.


https://github.com/corbindavenport/share-to-mastodon/assets/3879063/100c8cd2-cea7-473d-80a1-951c6cd646ee

**Comment by corq** [comment]
Thank you!

**Comment by Geobert** [comment]
Hi,

any news on a release with the fix?

Regards,

**Comment by corq** [comment]
Same, I've reinstalled and this behavior persists.

**Comment by corbindavenport** [comment]
This is rolling out now in the v2.2 update :)

**Comment by corq** [comment]
TY!
