### ISSUE TITLE
What's the format for adding the server links?

### ISSUE THREAD

**Issue by Newman5** [corbindavenport/share-to-mastodon#6]
I'm having trouble getting it set up.  Any documentation out there?

**Comment by corbindavenport** [comment]
You should be able to enter just the domain, like: `mastodon.social` or `toot.cafe`.

**Comment by Newman5** [comment]
Ah!  First I tried with https://mastodon.social/home... and I got an error with the https

Then, I tried with mastodon.social/home... and I got a different error

And, finally, it worked with 'mastodon.social'

Thanks!!

**Comment by corbindavenport** [comment]
Glad it worked! This is sort of related to #4, there should be better handling/explanation for server URLs in future updates.
